<?php


$subj=array('Calculus','Engineering Physics','Engineering Chemistry','Engineering Mechanics','Introduction to Computing and Problem Solving','Introduction to Civil Engineering','Introduction to Mechanical Engineering','Introduction to Electrical Engineering','Introduction to Electronics Engineering','Introduction to Chemical Engineering','Introduction to Sustainable Engineering','Basics of Mechanical Engineering','Basics of Electrical Engineering','Basics of Electronics Engineering','Basics of Civil Engineering','Physics Lab','Chemistry Lab','Civil Engineering Workshop','Mechanical Engineering Workshop','Electrical Engineering Workshop','Electronics Engineering Workshop','Computer Science Engineering Workshop','Discrete Computational Structures','Switching Theory and Logic Design','Data Structures','Electronics Devices and Circuits','Data Structures Lab','Electronic Circuits Lab','Mechanics of Solids','Mechanics of Fluids','Thermodynamics','Metallurgy and Materials Engineering','Circuits and Networks','Analog Electronic Circuits','DC Machines And Transformers','Computer Programming','Network Theory','Solid State Devices','Electronic Circuits','Logic Circuit Design','Mechanics of  Solids','Fluid Mechanics-I','Engineering Geology','Surveying','Computer Organization and Architecture','Operating Systems','Object Oriented Design and Programming','Principles of Database Design','Advanced Mechanics of Solids','Thermal Engineering','Manufacturing Technology','Fluid Machinery','Synchronous And Induction Machines','Digital Electronics And Logic Design','Material Science','Measurements and Instrumentation','Signals and Systems','Analog Integrated Circuits','Computer Organisation','Analog Communication Engineering','Structural Analysis-I','Construction Technology','Fluid Mechanics-II','Geotechnical Engineering-I','Theory of Computation','System Software','Microprocessors and Microcontrollers','Data Communication','Graph Theory and Combinatorics','Mechanics of Machinery','Machine Tools and Digital Manufacturing','Computer Programming and Numerical Methods','Electrical Drives and Control for Automation','Principles of Management','Power Generation, Transmission And Protection','Linear Control Systems','Power Electronics','Signals And  Systems','Microprocessor and Embedded Systems','Digital Signal Processing','Applied Electromagnetic Theory','Power Electronic And Instrumentation','Principles Of Managemnet','Design of Concrete Structures-I','Structural Analysis-II','Geotechnical Engineering','Geomatics','Water Resources Engineering');

echo $subj[68];
//87

?>
